# Generated by Django 5.2 on 2025-04-26 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_service', models.TextField(help_text='Décrivez le service que vous demandez pour cet article.')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_fixee', models.DateTimeField(blank=True, help_text="Date fixée par l'administrateur si la demande est acceptée.", null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_liees', to='articles.article')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
